"""
Build chart_data.js from CSV files.
Converts ZC, ZS, ZW H1 CSV data into a JavaScript file
that can be loaded directly in the browser.
"""
import csv
import os
import json

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.dirname(BASE_DIR)

CSV_FILES = {
    'ZC': os.path.join(PARENT_DIR, 'ZC_active_H1.csv'),
    'ZS': os.path.join(PARENT_DIR, 'ZS_active_H1.csv'),
    'ZW': os.path.join(PARENT_DIR, 'ZW_active_H1.csv'),
}

LABELS = {
    'ZC': 'Corn (ZC)',
    'ZS': 'Soybeans (ZS)',
    'ZW': 'Wheat (ZW)',
}

def parse_csv(filepath):
    candles = []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if not row.get('Time') or not row['Time'].strip():
                continue
            try:
                candles.append({
                    'time': row['Time'].strip(),
                    'open': float(row['Open']),
                    'high': float(row['High']),
                    'low': float(row['Low']),
                    'close': float(row['Close']),
                    'ema21': round(float(row['EMA_21']), 2),
                    'ema50': round(float(row['EMA_50']), 2),
                    'rsi': round(float(row['RSI']), 2),
                    'atr': round(float(row['ATR']), 4),
                    's1': float(row['S1']),
                    's2': float(row['S2']),
                    'r1': float(row['R1']),
                    'r2': float(row['R2']),
                })
            except (ValueError, KeyError) as e:
                print(f"  Skipping row: {e}")
                continue
    return candles

def main():
    all_data = {}
    for symbol, filepath in CSV_FILES.items():
        print(f"Parsing {symbol} from {filepath}...")
        if not os.path.exists(filepath):
            print(f"  WARNING: File not found: {filepath}")
            continue
        candles = parse_csv(filepath)
        all_data[symbol] = candles
        print(f"  Loaded {len(candles)} candles")

    output_path = os.path.join(BASE_DIR, 'chart_data.js')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated chart data from CSV files\n')
        f.write('// Generated by build_data.py\n\n')
        f.write('const CHART_DATA = ')
        json.dump(all_data, f, indent=None, separators=(',', ':'))
        f.write(';\n\n')
        f.write('const CHART_LABELS = ')
        json.dump(LABELS, f)
        f.write(';\n')

    size_kb = os.path.getsize(output_path) / 1024
    print(f"\nGenerated {output_path} ({size_kb:.1f} KB)")

if __name__ == '__main__':
    main()
